modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"

[[mods]]
modId = "deeperdarker"
version = "${version}"
displayName = "Deeper and Darker"
logoFile = "banner.png"
authors = "Kyanite Mods"
description = '''A Minecraft 1.19 mod which features more blocks, items, armors, and hidden mysteries to complement the new Deep Dark biome.'''

[[dependencies.deeperdarker]]
modId = "forge"
mandatory = true
versionRange = "[41.0.94,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.deeperdarker]]
modId = "paragon"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.deeperdarker]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.0.16,)"
ordering = "NONE"
side = "BOTH"