modLoader = "javafml"
loaderVersion = "[42,)"
license = "MIT"
issueTrackerURL = "https://github.com/KyaniteMods/DeeperAndDarker/issues"

[[mods]]
    modId = "deeperdarker"
    version = "1.0.0b"
    displayName = "Deeper And Darker"
    displayURL = "https://github.com/KyaniteMods/DeeperAndDarker"
    logoFile = "banner.png"
    authors = "Kyanite Mods"
    description = '''A Minecraft 1.19 mod which features more blocks, items, armors, and hidden mysteries to complement the new Deep Dark biome.'''

[[dependencies.deeperdarker]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19, 1.20)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.deeperdarker]]
    modId = "forge"
    mandatory = true
    versionRange = "[42,)"
    ordering = "NONE"
    side = "BOTH"
